/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    clients: ClientAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clients: Client;
    media: Media;
    plans: Plan;
    microcycles: Microcycle;
    workouts: Workout;
    'workout-groups': WorkoutGroup;
    'workout-exercise-rows': WorkoutExerciseRow;
    'workout-logs': WorkoutLog;
    'round-logs': RoundLog;
    'set-logs': SetLog;
    'exercise-logs': ExerciseLog;
    exercises: Exercise;
    'share-links': ShareLink;
    'body-weight-logs': BodyWeightLog;
    'program-products': ProgramProduct;
    'program-orders': ProgramOrder;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    clients: {
      plans: 'plans';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    microcycles: MicrocyclesSelect<false> | MicrocyclesSelect<true>;
    workouts: WorkoutsSelect<false> | WorkoutsSelect<true>;
    'workout-groups': WorkoutGroupsSelect<false> | WorkoutGroupsSelect<true>;
    'workout-exercise-rows': WorkoutExerciseRowsSelect<false> | WorkoutExerciseRowsSelect<true>;
    'workout-logs': WorkoutLogsSelect<false> | WorkoutLogsSelect<true>;
    'round-logs': RoundLogsSelect<false> | RoundLogsSelect<true>;
    'set-logs': SetLogsSelect<false> | SetLogsSelect<true>;
    'exercise-logs': ExerciseLogsSelect<false> | ExerciseLogsSelect<true>;
    exercises: ExercisesSelect<false> | ExercisesSelect<true>;
    'share-links': ShareLinksSelect<false> | ShareLinksSelect<true>;
    'body-weight-logs': BodyWeightLogsSelect<false> | BodyWeightLogsSelect<true>;
    'program-products': ProgramProductsSelect<false> | ProgramProductsSelect<true>;
    'program-orders': ProgramOrdersSelect<false> | ProgramOrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Client;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ClientAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name?: string | null;
  /**
   * Used to calculate age in the athlete app
   */
  birthDate?: string | null;
  weightKg?: number | null;
  heightCm?: number | null;
  experienceLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  /**
   * Primary training goals for program design
   */
  trainingFocus?:
    | (
        | 'hypertrophy'
        | 'strength'
        | 'definition'
        | 'recomposition'
        | 'fat_loss'
        | 'maintenance'
        | 'muscular_endurance'
        | 'mobility'
        | 'recovery'
        | 'over_50'
      )[]
    | null;
  /**
   * Free-text goals visible to the athlete
   */
  goals?: string | null;
  plans?: {
    docs?: (number | Plan)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'clients';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  client?: (number | null) | Client;
  /**
   * Template plans have no client and can be sold via program products
   */
  isTemplate?: boolean | null;
  status?: ('active' | 'paused' | 'completed') | null;
  /**
   * Primary focus of this plan (for filtering and future analytics)
   */
  trainingType?:
    | (
        | 'hypertrophy'
        | 'strength'
        | 'definition'
        | 'recomposition'
        | 'fat_loss'
        | 'maintenance'
        | 'muscular_endurance'
        | 'mobility'
        | 'recovery'
        | 'over_50'
      )
    | null;
  startDate?: string | null;
  endDate?: string | null;
  title: string;
  description?: string | null;
  /**
   * Where the plan was imported from
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "microcycles".
 */
export interface Microcycle {
  id: number;
  title: string;
  plan: number | Plan;
  /**
   * Target RPE for the microcycle (6–9)
   */
  rpe?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts".
 */
export interface Workout {
  id: number;
  title: string;
  microcycle: number | Microcycle;
  rpe?: number | null;
  order?: number | null;
  sections?:
    | {
        /**
         * e.g. Warm-up, Main part
         */
        title?: string | null;
        /**
         * e.g. Upper Body, EMOM
         */
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-groups".
 */
export interface WorkoutGroup {
  id: number;
  workout: number | Workout;
  /**
   * Row ID of the section from workout.sections
   */
  sectionRowId?: string | null;
  /**
   * e.g. "Upper superset", "Main part A" (optional)
   */
  label?: string | null;
  order?: number | null;
  /**
   * Render this group in the same colored block as the group above it
   */
  bundleWithPrevious?: boolean | null;
  protocol?: ('standard' | 'emom' | 'amrap' | 'for_time' | 'tabata') | null;
  /**
   * e.g. "4", "1-3"
   */
  rounds?: string | null;
  /**
   * Used for AMRAP
   */
  durationMinutes?: number | null;
  /**
   * Used for EMOM — default 60
   */
  intervalSeconds?: number | null;
  /**
   * Used for Tabata — default 20
   */
  workSeconds?: number | null;
  /**
   * Used for Tabata — default 10
   */
  restSeconds?: number | null;
  /**
   * Rest after completing a full round/circuit
   */
  restBetweenRounds?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-exercise-rows".
 */
export interface WorkoutExerciseRow {
  id: number;
  group: number | WorkoutGroup;
  order?: number | null;
  /**
   * e.g. "1a", "2b"
   */
  numer?: string | null;
  /**
   * Link to the catalog — for video and progress tracking
   */
  exercise?: (number | null) | Exercise;
  note?: string | null;
  targetType?: ('repetitions' | 'duration') | null;
  /**
   * e.g. 4, 3-4
   */
  rounds?: string | null;
  reps?: string | null;
  repsLeft?: string | null;
  repsRight?: string | null;
  kg?: string | null;
  tut?: string | null;
  rir?: string | null;
  rest?: string | null;
  durationMin?: number | null;
  durationSec?: number | null;
  /**
   * Fill in only for drop sets / pyramids. Empty = all sets identical.
   */
  setParameters?:
    | {
        setNumber: number;
        reps?: string | null;
        kg?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty if the exercise inherits the protocol from the group.
   */
  override?: {
    protocol?: ('' | 'standard' | 'emom' | 'amrap' | 'for_time' | 'tabata') | null;
    rounds?: string | null;
    durationMinutes?: number | null;
    intervalSeconds?: number | null;
    workSeconds?: number | null;
    restSeconds?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises".
 */
export interface Exercise {
  id: number;
  name: string;
  /**
   * Determines which fields are shown in the set logging form
   */
  trackingType?: ('strength' | 'cardio') | null;
  description?: string | null;
  /**
   * URL to instructional video (e.g. YouTube)
   */
  videoUrl?: string | null;
  muscleGroup?: string | null;
  equipment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-logs".
 */
export interface WorkoutLog {
  id: number;
  /**
   * Auto-generated
   */
  title?: string | null;
  workout: number | Workout;
  client?: (number | null) | Client;
  startedAt?: string | null;
  finishedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "round-logs".
 */
export interface RoundLog {
  id: number;
  session: number | WorkoutLog;
  group: number | WorkoutGroup;
  client?: (number | null) | Client;
  roundNumber: number;
  startedAt?: string | null;
  finishedAt?: string | null;
  status?: ('completed' | 'partial' | 'skipped') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "set-logs".
 */
export interface SetLog {
  id: number;
  session: number | WorkoutLog;
  client?: (number | null) | Client;
  exercise?: (number | null) | Exercise;
  exerciseName?: string | null;
  exerciseRow?: (number | null) | WorkoutExerciseRow;
  roundLog?: (number | null) | RoundLog;
  setNumber?: number | null;
  weight?: number | null;
  weightLeft?: number | null;
  weightRight?: number | null;
  isBodyweight?: boolean | null;
  distanceM?: number | null;
  durationSec?: number | null;
  reps?: string | null;
  repsLeft?: string | null;
  repsRight?: string | null;
  rir?: string | null;
  rpe?: number | null;
  note?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-logs".
 */
export interface ExerciseLog {
  id: number;
  session: number | WorkoutLog;
  client?: (number | null) | Client;
  exercise?: (number | null) | Exercise;
  exerciseName?: string | null;
  exerciseRow: number | WorkoutExerciseRow;
  roundLog?: (number | null) | RoundLog;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-links".
 */
export interface ShareLink {
  id: number;
  /**
   * Optional name to identify this link
   */
  label?: string | null;
  plan: number | Plan;
  /**
   * Auto-generated on first save
   */
  token?: string | null;
  permissions: ('plan' | 'results')[];
  /**
   * Link stops working after this date
   */
  expiresAt: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-weight-logs".
 */
export interface BodyWeightLog {
  id: number;
  client?: (number | null) | Client;
  recordedAt: string;
  weightKg: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-products".
 */
export interface ProgramProduct {
  id: number;
  title: string;
  /**
   * Used in /programmi/[slug]
   */
  slug: string;
  published?: boolean | null;
  featured?: boolean | null;
  /**
   * e.g. 4900 = €49.00
   */
  priceCents: number;
  currency?: ('eur' | 'pln' | 'usd') | null;
  /**
   * Optional — if set, checkout uses this Stripe price instead of ad-hoc amount
   */
  stripePriceId?: string | null;
  /**
   * Plan cloned and assigned to the buyer after successful payment
   */
  templatePlan: number | Plan;
  /**
   * Shown on catalog cards
   */
  shortDescription?: string | null;
  description?: string | null;
  durationWeeks?: number | null;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-orders".
 */
export interface ProgramOrder {
  id: number;
  product: number | ProgramProduct;
  client?: (number | null) | Client;
  assignedPlan?: (number | null) | Plan;
  email: string;
  status: 'pending' | 'paid' | 'failed' | 'refunded';
  amountCents?: number | null;
  currency?: string | null;
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  /**
   * e.g. temporary password for newly created client accounts
   */
  fulfillmentNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'microcycles';
        value: number | Microcycle;
      } | null)
    | ({
        relationTo: 'workouts';
        value: number | Workout;
      } | null)
    | ({
        relationTo: 'workout-groups';
        value: number | WorkoutGroup;
      } | null)
    | ({
        relationTo: 'workout-exercise-rows';
        value: number | WorkoutExerciseRow;
      } | null)
    | ({
        relationTo: 'workout-logs';
        value: number | WorkoutLog;
      } | null)
    | ({
        relationTo: 'round-logs';
        value: number | RoundLog;
      } | null)
    | ({
        relationTo: 'set-logs';
        value: number | SetLog;
      } | null)
    | ({
        relationTo: 'exercise-logs';
        value: number | ExerciseLog;
      } | null)
    | ({
        relationTo: 'exercises';
        value: number | Exercise;
      } | null)
    | ({
        relationTo: 'share-links';
        value: number | ShareLink;
      } | null)
    | ({
        relationTo: 'body-weight-logs';
        value: number | BodyWeightLog;
      } | null)
    | ({
        relationTo: 'program-products';
        value: number | ProgramProduct;
      } | null)
    | ({
        relationTo: 'program-orders';
        value: number | ProgramOrder;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'clients';
        value: number | Client;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  birthDate?: T;
  weightKg?: T;
  heightCm?: T;
  experienceLevel?: T;
  trainingFocus?: T;
  goals?: T;
  plans?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  client?: T;
  isTemplate?: T;
  status?: T;
  trainingType?: T;
  startDate?: T;
  endDate?: T;
  title?: T;
  description?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "microcycles_select".
 */
export interface MicrocyclesSelect<T extends boolean = true> {
  title?: T;
  plan?: T;
  rpe?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workouts_select".
 */
export interface WorkoutsSelect<T extends boolean = true> {
  title?: T;
  microcycle?: T;
  rpe?: T;
  order?: T;
  sections?:
    | T
    | {
        title?: T;
        subtitle?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-groups_select".
 */
export interface WorkoutGroupsSelect<T extends boolean = true> {
  workout?: T;
  sectionRowId?: T;
  label?: T;
  order?: T;
  bundleWithPrevious?: T;
  protocol?: T;
  rounds?: T;
  durationMinutes?: T;
  intervalSeconds?: T;
  workSeconds?: T;
  restSeconds?: T;
  restBetweenRounds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-exercise-rows_select".
 */
export interface WorkoutExerciseRowsSelect<T extends boolean = true> {
  group?: T;
  order?: T;
  numer?: T;
  exercise?: T;
  note?: T;
  targetType?: T;
  rounds?: T;
  reps?: T;
  repsLeft?: T;
  repsRight?: T;
  kg?: T;
  tut?: T;
  rir?: T;
  rest?: T;
  durationMin?: T;
  durationSec?: T;
  setParameters?:
    | T
    | {
        setNumber?: T;
        reps?: T;
        kg?: T;
        id?: T;
      };
  override?:
    | T
    | {
        protocol?: T;
        rounds?: T;
        durationMinutes?: T;
        intervalSeconds?: T;
        workSeconds?: T;
        restSeconds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workout-logs_select".
 */
export interface WorkoutLogsSelect<T extends boolean = true> {
  title?: T;
  workout?: T;
  client?: T;
  startedAt?: T;
  finishedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "round-logs_select".
 */
export interface RoundLogsSelect<T extends boolean = true> {
  session?: T;
  group?: T;
  client?: T;
  roundNumber?: T;
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "set-logs_select".
 */
export interface SetLogsSelect<T extends boolean = true> {
  session?: T;
  client?: T;
  exercise?: T;
  exerciseName?: T;
  exerciseRow?: T;
  roundLog?: T;
  setNumber?: T;
  weight?: T;
  weightLeft?: T;
  weightRight?: T;
  isBodyweight?: T;
  distanceM?: T;
  durationSec?: T;
  reps?: T;
  repsLeft?: T;
  repsRight?: T;
  rir?: T;
  rpe?: T;
  note?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercise-logs_select".
 */
export interface ExerciseLogsSelect<T extends boolean = true> {
  session?: T;
  client?: T;
  exercise?: T;
  exerciseName?: T;
  exerciseRow?: T;
  roundLog?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exercises_select".
 */
export interface ExercisesSelect<T extends boolean = true> {
  name?: T;
  trackingType?: T;
  description?: T;
  videoUrl?: T;
  muscleGroup?: T;
  equipment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "share-links_select".
 */
export interface ShareLinksSelect<T extends boolean = true> {
  label?: T;
  plan?: T;
  token?: T;
  permissions?: T;
  expiresAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-weight-logs_select".
 */
export interface BodyWeightLogsSelect<T extends boolean = true> {
  client?: T;
  recordedAt?: T;
  weightKg?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-products_select".
 */
export interface ProgramProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  featured?: T;
  priceCents?: T;
  currency?: T;
  stripePriceId?: T;
  templatePlan?: T;
  shortDescription?: T;
  description?: T;
  durationWeeks?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-orders_select".
 */
export interface ProgramOrdersSelect<T extends boolean = true> {
  product?: T;
  client?: T;
  assignedPlan?: T;
  email?: T;
  status?: T;
  amountCents?: T;
  currency?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  fulfillmentNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}