import React from 'react'

export const s = {
  container: { padding: '20px 24px', fontFamily: 'var(--font-body)' } as React.CSSProperties,
  header: { marginBottom: 16 } as React.CSSProperties,
  sectionBlock: { marginBottom: 28 } as React.CSSProperties,
  sectionHeader: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    marginBottom: 10,
    paddingBottom: 6,
    borderBottom: '1px solid var(--theme-border-color)',
  },
  groupCard: {
    background: 'var(--theme-elevation-100)',
    border: '1px solid var(--theme-border-color)',
    borderRadius: 'var(--style-radius-l)',
    marginBottom: 10,
    overflow: 'hidden',
  } as React.CSSProperties,
  groupHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    background: 'var(--theme-elevation-150)',
    borderBottom: '1px solid var(--theme-border-color)',
  } as React.CSSProperties,
  groupTitle: { fontSize: 12, fontWeight: 600, color: 'var(--theme-text)' } as React.CSSProperties,
  groupMeta: { fontSize: 11, color: 'var(--theme-elevation-500)', marginLeft: 8 } as React.CSSProperties,
  exerciseRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '8px 12px',
    borderBottom: '1px solid var(--theme-elevation-100)',
    gap: 8,
  } as React.CSSProperties,
  exerciseNumer: { fontSize: 11, fontWeight: 700, color: '#6E52EB', minWidth: 20 } as React.CSSProperties,
  exerciseName: { fontSize: 13, color: 'var(--theme-text)', flex: 1 } as React.CSSProperties,
  exerciseMeta: { fontSize: 11, color: 'var(--theme-elevation-500)' } as React.CSSProperties,
  formBox: {
    background: 'var(--theme-elevation-50)',
    border: '1px solid var(--theme-border-color)',
    borderRadius: 'var(--style-radius-l)',
    padding: '12px 14px',
    marginTop: 8,
  } as React.CSSProperties,
  formRow: { display: 'flex', gap: 8, flexWrap: 'wrap' as const, marginBottom: 8 } as React.CSSProperties,
  label: { fontSize: 'var(--base-body-size)', color: 'var(--theme-elevation-500)', display: 'block', marginBottom: 3 } as React.CSSProperties,
  input: {
    background: 'var(--theme-input-bg)',
    border: '1px solid var(--theme-border-color)',
    borderRadius: 'var(--style-radius-s)',
    color: 'var(--theme-text)',
    fontFamily: 'var(--font-body)',
    fontSize: 'var(--base-body-size)',
    padding: '5px 8px',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  formActions: { display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 10 } as React.CSSProperties,
  empty: { fontSize: 12, color: 'var(--theme-elevation-500)', padding: '8px 12px', fontStyle: 'italic' as const },
  errorMsg: { fontSize: 12, color: 'var(--theme-error-500)', marginBottom: 8 },
  infoMsg: {
    fontSize: 12,
    color: 'var(--theme-elevation-500)',
    background: 'var(--theme-elevation-50)',
    border: '1px solid var(--theme-border-color)',
    borderRadius: 'var(--style-radius-m)',
    padding: '8px 12px',
    marginBottom: 20,
  } as React.CSSProperties,
}
